Added collection of git commit info to build script.

diff --git a/NEMOGCM/CONFIG/makenemo b/NEMOGCM/CONFIG/makenemo
--- a/NEMOGCM/CONFIG/makenemo
+++ b/NEMOGCM/CONFIG/makenemo
@@ -359,6 +359,26 @@ grep key_agrif ${COMPIL_DIR}/cpp.fcm && export AGRIFUSE=1 && export USEBLD=${USE
 if [ "${NBR_PRC}" -gt 0 ]; then
     cd ${NEMO_TDIR}/${NEW_CONF} || cd -
 
+    #-
+    #- Get git version information if available
+    mkdir -p ${CONFIG_DIR}/${NEW_CONF}/BLD/inc
+    GITVERSIONHEADER=${CONFIG_DIR}/${NEW_CONF}/BLD/inc/gitversion.h90
+    echo "Extracting git commit info into" $GITVERSIONHEADER
+    NEMOCOMMIT=$( git describe --always --dirty )
+    if [ $? -ne 0 ]
+    then
+       echo "Unable to extract git commit info!"
+       NEMOCOMMIT="NOT AVAILABLE"
+    fi
+    echo "#define _NEMO_COMMIT_ID_ ${NEMOCOMMIT}" > ${GITVERSIONHEADER}
+    NEMOBRANCH=$( git name-rev --name-only HEAD )
+    if [ $? -ne 0 ]
+    then
+       echo "Unable to extract git branch info!"
+       NEMOBRANCH="UNKNOWN"
+    fi
+    echo "#define _NEMO_BRANCH_ ${NEMOBRANCH}" >> ${GITVERSIONHEADER}
+
 #if AGRIF we do a first preprocessing
     if [ ${#x_c} -eq 0 ]; then
        if [ "$AGRIFUSE" == 1 ]; then 
